# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      frame:
        required: true
        type: string
      token:
        type: string
      board:
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Hide the inputs values to keep them private in the logs when running this workflow
      uses: levibostian/action-hide-sensitive-inputs@v1
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - run: npx miro-export -t "${{ secrets.TOKEN || github.event.inputs.token }}" -b "${{ secrets.BOARD || github.event.inputs.board }}" -f "${{github.event.inputs.frame}}" -o "{frameName}.svg"
    - uses: actions/upload-artifact@v4
      with:
        name: ${{github.event.inputs.frame}}
        path: ${{github.event.inputs.frame}}.svg
